"use client"

import { useState } from "react"
import Link from "next/link"
import Header from "@/components/header"
import Footer from "@/components/footer"
import HomeButton from "@/components/home-button"
import { useLanguage } from "@/components/language-context"
import "@/styles/class-details.css"

export default function ClassPage({ params }: { params: { classNumber: string } }) {
  const { t } = useLanguage()
  const [expandedSubject, setExpandedSubject] = useState<string | null>(null)

  const subjectsData = [
    { name: t("Physics"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1cG43NFq8ZFyDbaRznm3MgVf20Lvu-Jgo" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pF-5R_Q7cdXvOectDbRFhd" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1C-CGGqrAqMsWhuW9LnvVZcYgl6hw-1UF" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1qbrkXiJ3VbjOCp7dLdMr6QpkXQhXb6A-" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-puW9kBL4q2pmRUdJHkLWVr" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pGPlO3MNqZ9cCKKzjzLlD_" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("Chemistry"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/18VA9ZwBSteC3sHGR1vF2LkxGcN0o-qSN" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-o8Nsd6TuptRwZECUivy8aa" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1jv8sDHtetQco2W7clPUKDhOMiMnb9fb6" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1db9ZMlcyytz62c8bVFC4tiOuMO-ubxrk" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pUjXmrjhyHBaVR4iajKkjc" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qozoiXi5OnWOmqzARVzl0L" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("mathematics"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1GitJ4IeSntN0po2IaFEdZwA_kwy3ZieZ" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oILckvJkQwjowMKn1iEa_1" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1gkYvRXSiMlStJbrzWjwu6U-epVgGMQ34" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/15TX6T8ckU5JVvRFLKWE65BrLZcSO8wOP" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qwY42wGfYBO1Rgb-nbkPo3" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qiHVXODl5VN05wKKTTzVgn" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("biology"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1Px-MV6Qs_Ij4VIXEfulmMVYBPEHkk54k" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rLhrigDqaOT69m3kP0E4YH" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1Odlyd-jeHXz_4JqAvVXmdISO1jtNtTug" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1dXqFkdFvhPpnzyPhl_n4Kwow_YxqAMTX" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qBHwgqjm0qiX7yahyJbCdH" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pg8RoOax13TLkgnJK1SIy4" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("computer"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1WYZKQm8uqlGJLOmU1ML1kai0vVl2PvlF" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-q_CWYBRKenUiyAG_OroH5P" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1oXlXOElz8XzPAEeTl7P35hHNbGmo74eh" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1peWN3KuHKt5HKOpVWmAWmKxRRIceeyOI" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qMcHhyfcd_5thCf9vqRCuG" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rlHgqncIGJdxEQUgZF9xCx" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("history"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1zshIqyHn6Iy813wI7EpDRtcWRP9zEiCH" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-q4A7zFGFF4Up-kCsJtFyFB" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1JBtXRe0_R2kzs5ZEspIxT2kImqWMI_Qh" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/18wZm9zimrejZ_fCEdjP3Ev0SYWQO8o19" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qlDLVChvG0OIQg4nDH2AJL" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oKSuESknAg-gc7PW74R1Tv" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("geography"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1z_SDmw6ZP18R2xMwCCaC4GduBQecnNVR" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qBUJk9AQESEq5YAYpo1ipv" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1Y3O_g3qkhLnWtcIzXtsWovXIaenpjq5s" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/10sXjwF-2LibVSy9btUV6-Qcavk1bPSTy" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pYHbKlWNBmAKw9GmIb4Oia" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-p5P3yxdZLFIVFyTfCoRGhE" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("Civics"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1xFgqyBHsRHDqxZOIPwbkNa7sdAbLRXHp" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oNFFu82Vto1YB2jOo71tSN" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1Ae0XeE7HDujUWAv5mvDqCn2FcIIMuxPj" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1Je2oeEJLhVQwImWKTCKcfuMDQN2QrLCb" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qVNxtVDbTY5GeCr7hYNixA" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qKFkb-Crv8C73EXZ5rLpmi" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("politicalScience"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1n8iAXHSxaYxagttR5668cN_L5xdir721" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qOoknomPB3Gz-5ho3K-veR" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1LRx28PKZDr0JQ48aQUfgiEht6LT_9zhr" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1wsLhl7JTOJt4MNFFpwk1kVhr6GmfYrUo" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oNSJTMbnRyXQdU9bcd3bsl" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qKqueXacMe6uw7msysUVuI" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("Sociology"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1dwTqhAGElf5WEZqNZ8WTDkCP9ueHw8fc" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-r5wV-Cm_RRLIL0BgjE88xg" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1odWA_nsdxpm_nevukJqeENaHfrl_DTgT" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1Wj2A8hb_1ugn54tJsw_3GElJd4GKpHF_" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-o8UHNhltjGOWCi2CNK6hsI" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-revSTq6bKkb_xHj4faEI1w" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("Psychology"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1Yk6Itmcft7A-O1eUb5iA2VV3MQEZ8h2L" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qwXAfu0qoWrjLgXL8_yUVS" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/13_OSUGbU65YM0RERsQGiYOzQCIZbqetV" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1NOG2zzVDHafTiYa0LeuiTr47iFgPsnnz" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pY63lm_b1ETOlKBeGWVlBK" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pKhwAq0pW_y5YJaLhsUtQ2" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("education"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1UKdZ1rJ3rg1vmLxbbKNAy-dFf2Iiiefa" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qjNhmOnMMXwYWGX9kK9_YJ" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/16xVWsGi1yDAcw2oh1u5354C5-jeHgTMr" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1xEOroqrtlZMNGHUPPGfL6vDRs_f2jhpI" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oNUtfQUuCmH6uaRsljhHKo" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pJRwmjwAOZmfStyNuHLo1-" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("economics"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1KIBUOiKCKD4FayBzm2aR0cgLEX5QFCJG" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-olvliFhTaP9B5YCimnaQhA" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1h1SyBs2ipTP6buL1cgiJK78EaJoXX-8y" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1eeccksSpzu1wCznAgSdvE0i_pakmkpmy" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qJds7R6Cs27HbGCbZ8g4sX" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oBg9Rmp5FFFFIoLoIXLQyp" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("accountancy"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/13xhwSXOrM_XwxfmgGrqPb99q3ckTVUHi" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qXf3sBkJGSefS9gZVKPrNv" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1e2-6dOePGels--UQWqaGX-bS1vHpIRI1" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/12chV3O1BsIEEmnEttfG3PMi7AoJidkTx" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qq6cbZGXk86onxYEf6UH8H" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qq6cbZGXk86onxYEf6UH8H" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("businessStudies"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1BLfybucgs_0L6yn1naSNeqdPGTkiG2J9" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oPLCCkK7HmlyQLt7Z-12hY" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1O_RUQ0Gle6y1l5ASLEXcgjN5ymt2jhDv" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1jQQsbXRevgvoOILuhaDM4TSaCVC3bZe7" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oEqCqeXvase3P5OebJCi80" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qveJh8aMaazT_S0lmeWdpa" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("hindi"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1Z0DBMnF6T4dC3GCFGfWWH20G3TFqi3IK" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rjcsKpgJInyLIdGuQvklSa" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/10Mr9W_0M3dkKN5iWY8AGwJwaRaD_dA5z" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1z9K1VUX4vy58HGNP2dArTeeaTNl8tupU" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-q9y6P8UA3T72KOcaHnTWBI" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qeiQsSFUoycezUgv1gGoQY" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("GeneralHindi"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1abL0pjhePAgHJh4Nnqr8qtLS2hn8pP80" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oEVOyBW8kpl_Ag0VzyQSZr" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1nIytobKZ27VrEGvh4gOce2hY3MVXJY37" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1PSVp_XeSPjzNKOMF-OwMNrDVSngOuraf" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-odx7-R0-FNt0Eug7AkjJLa" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qr1nCl9YNvWCmJmkbp1kxM" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("english"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/11FFk4IEZVBhYxQk2D_C6kDKcAPqMnMYM" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qv3ZOTevvkGCG1KBW_jG3c" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1jmQFEzQRKaXmts020iq9ytmoOQbuAuIy" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1GPRvowXU_kEVxRBYaDq4cBYjnJcbRZu8" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oPdvOul_hHd7fPjRNgDux9" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oNhCaNSQPSUkDtj5ga2FwD" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
  ]

  const toggleSubject = (subject: string) => {
    setExpandedSubject(expandedSubject === subject ? null : subject)
  }

  return (
    <div title="Class 11 Courses and Learning Resources - Science, Commerce and Humanities">
      <Header />
      <main className="class-details-container" title="Class 11 subject courses and study materials">
        <div className="class-details-header" title="Class 11 page header with course overview">
          <h1 title="Class 11 courses and subjects">{t("class11")}</h1>
          <p title="Explore all available subjects for Class 11">{t("exploreAllSubjects")}</p>
        </div>

        <div className="subjects-container" title="Grid of Class 11 subjects with expandable options">
          {subjectsData.map((subject) => (
            <div key={subject.name} className="subject-card" title={`${subject.name} subject courses and resources`}>
              <button
                className="subject-header"
                title={`Expand or collapse ${subject.name} subject options`}
                onClick={() => toggleSubject(subject.name)}
              >
                <span className="subject-name" title={`Subject: ${subject.name}`}>{subject.name}</span>
                <span className={`subject-toggle ${expandedSubject === subject.name ? "open" : ""}`} title="Toggle to view options">
                  ▼
                </span>
              </button>

              {expandedSubject === subject.name && (
                <div className="subject-options" title={`Learning resources for ${subject.name}`}>
                  {subject.options.map((option, index) => (
                    <Link href={option.link} key={index} className="option-link" title={`Access ${option.name} for ${subject.name}`} target="_blank" rel="noopener noreferrer">
                      <div className="option-card" title={`${option.name} resource card`}>
                        <img src={option.icon} alt={`${option.name} for ${subject.name}`} className="option-icon" title={`Icon for ${option.name}`} />
                        <div className="option-name" title={`Resource type: ${option.name}`}>{option.name}</div>
                        <div className="option-arrow" title="Open resource">→</div>
                      </div>
                    </Link>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      </main>
      <HomeButton />
      <Footer />
    </div>
  )
}
