"use client"

import { useState } from "react"
import Link from "next/link"
import Header from "@/components/header"
import Footer from "@/components/footer"
import HomeButton from "@/components/home-button"
import { useLanguage } from "@/components/language-context"
import "@/styles/class-details.css"

export default function ClientClass12({ params }: { params: { classNumber: string } }) {
  const { t } = useLanguage()
  const [expandedSubject, setExpandedSubject] = useState<string | null>(null)

  const subjectsData = [
    { name: t("Physics"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1TPD_miXrJTGC73lVpeByiY9qA7NXpMtP" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qisxlcV2yXubIZthUVYOw_" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1NMNF8fCNPQ1IFR5rsZc4IVXkFfltydSa" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1M8NI4VFaTpWyfhqlGXSy5q901hTy3YFz" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-o0gFc4OY1GNOmBHsAUshoM" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-q1RZloWq9p5pV5k2mOPIig" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("Chemistry"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1uQ44iYnMgZm6PiQjsw9BWPV6ThE5yixh" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qaGjtBfgHhzTGsH4FyTKGC" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/14kA1ga2GHJJBMtBoV2TTul5gKVHOWkCt" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1dfOFuUGEBirPF75Zyn6GioNrX-pgHHq2" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pqpBBT3C4mSGAH8_2Iy8nz" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rG2Y2cRfjGYQ-GRLvVCnXi" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("mathematics"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1cXGIGVOYY9MdBwhPhsjdVkx9Y1cwkdPP" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rhCk4EiMquwWcFZfxdOqXi" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1EKoTjqOxVWPy5zQGqfKl-ae0WY_a9kNJ" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/14FYom13QKXJdnBhRPtD0r-29VmrU1tIb" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-piu_vgU20r5RDa3pkKhBVQ" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rTHsJqXwz1Km3oryaBc6DK" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("biology"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1BGGRxyPqYEi1_rnzJ00o0ev9hG_wEdq8" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rOptcEuZNeR01W2UFzB48v" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1ulkLYjsnQkx85JTZTpmwl4Rxcr-jgjJc" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1OdNG1LZNeoeZlruY45xWDg1g1__iF38I" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-r5b3F1c6l1Ko2F4_Rqd0Ns" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qwUZho4qVNYAsL9Ux7g2Yv" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("computer"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1wFMv4QJ9UA9cYlQ7YylpojKdn6dB5qjp" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oaB82k4wIMWF-ho_sdE64i" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1XM94_PsvHbhsLReubwXx32MaPiuQyJ1t" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1FUpcQq1C-iY6mghAB08W6C2mMR4ReWDA" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oJ-5hYPNHCrvIKH5kfTef2" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-r-4BmT04SRoS2DutFExids" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("history"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1qvUNMFWMfhNyTvZhqLO5xPO953hGPIyD" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-r0S-RzGTWIX-qxeW0rSeVq" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1asQQiOfONMIHLuDqi1Js1jWbjcbtrLpO" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1jAR_OEOtGGhQL_vsSKyykp_f0GrFDrlt" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qEx3lklMDY97Ad9ww7zC5M" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-r7sUfas36YArVSZGXCdb9e" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("geography"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1bs-Ibc82cbFIiS6vqlGjmt3OhUGc93ZO" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rc9DPws4nVWizLyP2ntWxM" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1HHwqvXDqHpj9JfkocS8fl9oqthpKakun" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1KBfs1pzv2ke8IFLuy2bwQcd5HiTC0dOh" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oAeizyVXKhIoThkeP1pap9" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-q7mzejh_1iCzLRM39_5iJ7" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("Civics"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1UPKMGWZivfUGDJA65Uz-ZmPs_aGPE4Ai" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-ptKzDg3SRlLHsOSXvliL2u" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1Kp27TsK-QG8GnEmKYVq_GEz-NgKzBeRB" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1p_ZOoAw3CZigd0WHq6FmppCunxXnopam" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qGnNrQzTc8Q-xGJijDlmwZ" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pKF6YSspO7PC8jdehEU0zZ" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("politicalScience"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1yNG05CFhc7fy5vNeL95h56UqgMplZEV_" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-okOIlCa5MzyEbg_-7ddW3z" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1lQbwPwhtoMbfh4Lt0_K7xA_5BNF1jfCz" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1QAXucuvAMrv3wuM_6UcagrbGBrFxtNbp" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oAPcdMPL63hZypw_lChj90" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oC6a3hF7BuXYTd6Bnb3r8G" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("Sociology"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1I0WYFv3ZSDXbQ44qaJh9eUdDmvvn4Tv6" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oPHXvW12e3yxduwbl3IlBI" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/16GT6v1A40lvqklvIkWJbadsPxYwsSsAp" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1My70nZVgcHelcR6rUFp2POp6dSEMB2kM" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oVC0AGhqlm0JZ-aRXubNvx" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qSK46TvltMkncRMtwR--yb" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("Psychology"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/13JNhopEkIymjMG890MSRtm4IXThEe7bk" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rZqkBvOWWavFlem-4Y3uQQ" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1dI4W8Hs00dD7IAk78br4hx6_6YAuOfQa" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1Md12XURMrfBSfshSaRJfkEh3HalGmK79" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pow1yC1vdAh0hE1MlE5aTu" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qFerTsmGcTxyYd0KaAdNBY" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("education"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1TEaZ3qHX7YGz4PTZQ5jiXbJXwBvCtcOH" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rOG-hPnDwz64NJvNYFqlEH" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1ajc23kB8he4FVb4DzSf0F5o4kn3A9T9m" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1ajuLVRBCRpDOgiGdzGsrWSmehajqcXc3" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oMPwqHCjrWHc8_VsKzXLqY" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rKLJ3TCUINnyF-B5eCXswu" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("economics"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1qTF2g8eLmoqk3sS66k755wJHOboylWdI" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oNMe0_AbQ4PV1HhmPHB0ei" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1tiFb6a4S9NUgrrcdQkUrMVFPJ0Osc4a8" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1EfN0Vd3xvUuxWFK9WyBComb5FRJ7KVMt" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qEi4gu1NFBv1MpfPwjyb0d" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pnO_4N4pjOO3C4ZDQGT15d" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("accountancy"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1t_kPbMy3zRUnzQ_f0mmpoVtKgbLqwWrZ" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pMj3wikIsZiTqbgNRfmcco" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/11o0vqQ7jUTJVAhQSN2XTxHi4uANRRlEV" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1gZO9fpVe2AI7E-cQG19kyIVscIZ8CPbI" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-oHeAHl9xUk32ZLO_WQdqlp" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-q7CVVj0rrZYwi6ZY1yta0t" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("businessStudies"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1ec0shIbXzYw69NXcSbNlAvIP1-8vhoJs" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-q4iuhAT-jdj7vQh55-WFas" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/149GZfWiWizqgfMUvwXVX751-xaSVGXER" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1G5Zj-WuOQheHLWzz6ahhrBzqxf-JR4DN" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-q_T4NQvfaU5Pi7_GTR9-4j" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-prUuubkZUX4rNNaFa0MZY6" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("hindi"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1DFzXqWgdlXWrH_2ZxU14DBRY1eZaaf4B" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pqXf6K2ekLGu3mYoxGxXG0" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1fyGObKgOwSqyrLFiDO8UMjZ82dx4IA0r" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1S4EHwT-z9FKkXE2J_L7Dl-mrrQVD9TnC" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pIqrBA4nGcE7iqPs-MBi9y" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-p_aST9LiAXY_EF8JFm_bVB" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("GeneralHindi"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1JyEZfG9k_us4-Sxi99LCth-sXi3hJ7I5" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rF59i4rgAZVuarSn8LTCcI" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1lnjX5jeD1pILH7gb6n3Kbzk1cv3GEohx" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1OVhHQa_zIPbLiBLbVN8ZUaY6ZULMxumb" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-qksWxFijVJk78VEWOJsnbo" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-rqLIAOiHLB-sHNml9N-15J" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
    { name: t("english"), options: [{ name: t("syllabus"), icon: "/7.jpg", link: "https://drive.google.com/drive/folders/1dHLxGuUdfdp18kImEP2mLL3FPxoVYKMO" }, { name: t("watchVideoLesson"), icon: "/9.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-o8KI7bFuGFrWGcjo5ZvRot" }, { name: t("studyMaterial"), icon: "/8.jpg", link: "https://drive.google.com/drive/folders/1O5keTuiBMvIkP2YDgu1amrrQaXl8FX9n" }, { name: t("practiceQuestions"), icon: "/10.jpg", link: "https://drive.google.com/drive/folders/1lY13e_ZuawfF3X0DJQPCyiAFcfKGRfYA" }, { name: t("quickRevisionVideos"), icon: "/13.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-pDmf7hTX2cuf6F1YDzDIp7" }, { name: t("doubtSession"), icon: "/12.jpg", link: "https://www.youtube.com/playlist?list=PL8LuoZnQO2-p5ZIzeOfPdOuFzpIPqAcZq" }, { name: t("askYourDoubt"), icon: "/11.jpg", link: "https://forms.gle/GGemXkdjXmcDvzZKA" }] },
  ]

  const toggleSubject = (subject: string) => {
    setExpandedSubject(expandedSubject === subject ? null : subject)
  }

  return (
    <div title="Class 12 Courses and Learning Resources - Science, Commerce and Humanities">
      <Header />
      <main className="class-details-container" title="Class 12 subject courses and study materials">
        <div className="class-details-header" title="Class 12 page header with course overview">
          <h1 title="Class 12 courses and subjects">{t("class12")}</h1>
          <p title="Explore all available subjects for Class 12">{t("exploreAllSubjects")}</p>
        </div>

        <div className="subjects-container" title="Grid of Class 12 subjects with expandable options">
          {subjectsData.map((subject) => (
            <div key={subject.name} className="subject-card" title={`${subject.name} subject courses and resources`}>
              <button
                className="subject-header"
                onClick={() => toggleSubject(subject.name)}
                title={`Expand or collapse ${subject.name} subject options`}
              >
                <span className="subject-name" title={`Subject: ${subject.name}`}>{subject.name}</span>
                <span className={`subject-toggle ${expandedSubject === subject.name ? "open" : ""}`} title="Toggle to view options">
                  ▼
                </span>
              </button>

              {expandedSubject === subject.name && (
                <div className="subject-options" title={`Learning resources for ${subject.name}`}>
                  {subject.options.map((option, index) => (
                    <Link href={option.link} key={index} className="option-link" target="_blank" rel="noopener noreferrer" title={`Access ${option.name} for ${subject.name}`}>
                      <div className="option-card" title={`${option.name} resource card`}>
                        <img src={option.icon} alt={`${option.name} for ${subject.name}`} className="option-icon" title={`Icon for ${option.name}`} />
                        <div className="option-name" title={`Resource type: ${option.name}`}>{option.name}</div>
                        <div className="option-arrow" title="Open resource">→</div>
                      </div>
                    </Link>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      </main>

      <HomeButton />
      <Footer />
    </div>
  )
}

